CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS vehicles_db;
CREATE DATABASE IF NOT EXISTS traffic_db;
CREATE DATABASE IF NOT EXISTS incidents_db;
CREATE DATABASE IF NOT EXISTS notifs_db;
