version: '3.8'

services:
  #  serveur de base de donner
  mysql-db:
    image: mysql:8.0
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 60s
      timeout: 60s
      retries: 20
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  #  les microservices
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - JWT_SECRET=SuperCleSecretePourMonProjet2026
    depends_on:
      mysql-db:
        condition: service_healthy

  vehicles-service:
    build: ./vehicles-service
    container_name: vehicles-service
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - JWT_SECRET=SuperCleSecretePourMonProjet2026
    depends_on:
      mysql-db:
        condition: service_healthy

  traffic-service:
    build: ./traffic-service
    container_name: traffic-service
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - JWT_SECRET=SuperCleSecretePourMonProjet2026
    depends_on:
      mysql-db:
        condition: service_healthy

  incidents-service:
    build: ./incidents-service
    container_name: incidents-service
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - JWT_SECRET=SuperCleSecretePourMonProjet2026
    depends_on:
      mysql-db:
          condition: service_healthy

  notifications-service:
    build: ./notifications-service
    container_name: notifications-service
    ports:
      - "3004:3004"
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - JWT_SECRET=SuperCleSecretePourMonProjet2026
    depends_on:
      mysql-db:
        condition: service_healthy

  # 3. API GATEWAY
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "4000:4000"
    environment:
      - AUTH_URL=http://auth-service:3000/graphql
      - VEHICLES_URL=http://vehicles-service:3001/graphql
      - TRAFFIC_URL=http://traffic-service:3002/graphql
      - INCIDENTS_URL=http://incidents-service:3003/graphql
      - NOTIFICATIONS_URL=http://notifications-service:3004/graphql
    depends_on:
      - auth-service
      - vehicles-service
      - traffic-service
      - incidents-service
      - notifications-service
